scalar ID

type Query {
  user(id: ID!): User
}

type User {
  id: ID!
  email: String!
  bio: String
  comments: [Comment!]!
}

type Comment {
  id: ID!
  content: String!
  author: User!
}

scalar DateTime
